name: '0.5.$(date:yy)$(DayOfYear)$(rev:.r)-beta'

trigger:
  batch: true
  branches:
    include:
    - main
jobs:
- job: LinuxJob
  pool:
    name: Apption Pool
  workspace:
    clean: all
    
  variables:
    NetCoreVersion: '6.0.x'

  steps:
  - task: AzureKeyVault@1
    inputs:
      azureSubscription: 'Microsoft Partner Network(7c29ea79-bc0f-47ec-b360-2b4fe0db71e1)'
      KeyVaultName: 'ElementalVault '
      SecretsFilter: 'NugetAPISecret'
      RunAsPreJob: true

  - task: UseDotNet@2
    displayName: 'Use .NET Core sdk $(NetCoreVersion)'
    inputs:
     version: '$(NetCoreVersion)'
     includePreviewVersions: true

  - task: NodeTool@0
    displayName: 'install node'
    inputs:
      versionSpec: '15.x' 
      checkLatest: true

  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    inputs:
      arguments: '--configuration Release /p:Version=$(Build.BuildNumber)'
      
  - task: DotNetCoreCLI@2
    displayName: 'dotnet build'
    condition: failed()    
    inputs:
      arguments: '--configuration Release /p:Version=$(Build.BuildNumber)'

  - task: DotNetCoreCLI@2
    displayName: 'dotnet test'
    inputs:
      command: test
      arguments: '--no-restore --verbosity normal'

  - task: DotNetCoreCLI@2
    displayName: 'nuget push elemental'
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
    inputs:
      command: custom
      custom: nuget
      arguments: 'push MudBlazor.Forms/bin/Release/MudBlazor.Forms.$(Build.BuildNumber).nupkg --api-key $(NugetAPISecret) --source https://api.nuget.org/v3/index.json'

